### ISSUE TITLE
Description of mole error

### ISSUE THREAD

**Issue by mattrbeck** [mattcurrie/cgb-acid2#1]
Hey there! In my own experience, the description "Object Priority Mode (DMG/CGB)" for the mole error could potentially be a little misleading.

In my own experience, the cause was that sprites on CGB are prioritized by position OAM rather than by X-coordinate.

I'm making an issue rather than a PR because I'm sure you understand this better than I do, and I might just be misunderstanding something.

Thanks for your work on these :)

**Comment by mattcurrie** [comment]
Hi there!

The "Object Priority Mode" is referring to bit 0 of `$FF6C`. This register is set by the CGB boot ROM to toggle between CGB object priority (prioritise by OAM position) and DMG object priority (prioritise by X coordinate):

https://github.com/ISSOtm/gb-bootroms/blob/master/src/cgb.asm#L23

So the failure case would be if you're prioritising by X coordinate instead of OAM position. 

I'll add a note in the table clarifying what it refers to.

**Comment by mattrbeck** [comment]
Oh wild, I didn't even know that register existed. The Pan Docs don't reference it...

**Comment by mattcurrie** [comment]
Ah yeap :) I only just discovered its purpose earlier this year by playing with the register value before the boot ROM had locked out access to it. Also the official name for the register wasn't known until recently too.

**Comment by mattrbeck** [comment]
Great, thanks for the info and for updating the readme! :)
